#!/bin/bash
ping -c3 google.com

if [ $? -eq 0 ]
then
echo "sucess"
else
echo "not sucess"
fi

====================================

echo -n "username"
read a
grep -w $a /etc/passwd > /dev/null
if [ $? -eq 0 ]
then
echo "existi"
else
echo "not exist"
fi

